repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=25000']
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.1
    hooks:
      - id: ruff
        types_or: [python, pyi, jupyter]
        args:
        - --fix
      - id: ruff-format
        types_or: [python, pyi, jupyter]
  - repo: https://github.com/MarcoGorelli/polars-upgrade/
    rev: 0.3.2
    hooks:
      - id: polars-upgrade
        args: [--target-version=0.19.15]
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.16
    hooks:
      - id: validate-pyproject
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.24.0
    hooks:
      - id: commitizen-branch
        stages: [push]
