name: Run Benchmarks

on:
    workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        python-version: ["3.11"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install ".[test,performance]"
      - name: Benchmark
        run: pytest -k "test_benchmark" -vv -o log_cli=True -o log_level=INFO
