name: Run Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'functime/**'
      - 'pyproject.toml'
      - "tests/**"
      - '.github/workflows/test.yml'
  pull_request:
    types: [ review_requested ]
jobs:
  test-local:
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install ".[test]"
      - name: Test local functions
        run: pytest -k "not test_forecasters" --benchmark-disable

  test-prod:
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    runs-on: ubuntu-latest
    env:
      TOKEN_ID: ${{ secrets.FUNCTIME__PROD__TOKEN_ID }}
      TOKEN_SECRET: ${{ secrets.FUNCTIME__PROD__TOKEN_SECRET }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install ".[test]"
      - name: Authenticate to functime Cloud
        run: functime token set --token-id $TOKEN_ID --token-secret $TOKEN_SECRET  --no-verify
      - name: Test Cloud functions
        run: pytest -k "test_forecasters" --benchmark-disable

  test-staging:
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    runs-on: ubuntu-latest
    env:
      FUNCTIME_SERVER_URL: ${{ secrets.FUNCTIME__STAGING__SERVER_URL }}
      TOKEN_ID: ${{ secrets.FUNCTIME__STAGING__TOKEN_ID }}
      TOKEN_SECRET: ${{ secrets.FUNCTIME__STAGING__TOKEN_SECRET }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install ".[test]"
      - name: Authenticate to functime Cloud
        run: functime token set --token-id $TOKEN_ID --token-secret $TOKEN_SECRET  --no-verify
      - name: Test Cloud functions
        run: pytest -k "test_forecasters" --benchmark-disable
